### ISSUE TITLE
Supporting reading content in /sys/block?

### ISSUE THREAD

**Issue by Alston-Tang** [dtrugman/pfs#32]
Hi!

Would like to see is there any plan to support reading block device info from /sys/block/...? Not really procfs but is very similar regarding how the info is used and how to do the parsing.

**Comment by dtrugman** [comment]
Hi there!
Thanks for reaching out.
It sounds like a reasonable idea, and I'm definitely not against it. It probably shouldn't go under the same `procfs` object, but rather a new `sysfs`, but that's technical details we can sort out later.
Any specific files that you had in mind? Anything that is device-specific?

**Comment by Alston-Tang** [comment]
> It probably shouldn't go under the same procfs object, but rather a new sysfs

Makes sense!
> Any specific files that you had in mind? Anything that is device-specific?

I'm thinking of reading basic information of local SSD/HDD drives. So I guess I would be interested to read files under directories like /sys/block/sda or /sys/block/nvme0n1. And I would be interested in ./size for capacity, ./dev dev id and ./stat for IO stat at least for now.
Not sure all types of block devices have these three files but at least these files exist for /sys/block/loop[N] and /sys/block/ram[N] on my computer running cent os stream 8 with 5.12 kernel. So probably not a bad idea to support these types by the way.

I can try to implement an initial PR if I have time in next several weeks for preview (not guaranteed :P).

**Comment by dtrugman** [comment]
> So I guess I would be interested to read files under directories like /sys/block/sda or /sys/block/nvme0n1. And I would be interested in ./size for capacity, ./dev dev id and ./stat for IO stat at least for now.

Sounds legit!

> I can try to implement an initial PR if I have time in next several weeks for preview (not guaranteed :P).

Since this sounds like a big change, let me create a branch with an initial version of the `sysfs` object, locate all the files where I would expect to see them, and you would be able to build on top of that? That will also decrease the amount of work you'll have to do to have this feature production ready. Sounds good?

**Comment by Alston-Tang** [comment]
Sounds good! Thank you for working on that.

**Comment by dtrugman** [comment]
@Alston-Tang, took some time, but I implemented the code - pull request #33.
If you're still interested, feel free to play around with the branch.
I will either wait for your ACK or merge it to master after a few days if I don't hear back.

**Comment by Alston-Tang** [comment]
Sorry for the late reply and thank you so much for the initial implementation! I'll try this branch.

**Comment by dtrugman** [comment]
Of course. Let me know if you need any additions.
